server:
  port: 8080
  tomcat:
    max-threads: 20
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
    
logging:
  level:
    root : INFO
    com.coxautodev.graphql: DEBUG    
    